language: go

before_install:
  - nvm install --lts
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - make install
  - pushd ui && yarn && popd

go:
  - 1.14.x

script:
  - make
  - pushd ui && yarn build && popd
