version: '3'
services:
  leifdb0:
    build: .
    ports:
      - "8080:8080"
      - "16990:16990"
    environment:
      LEIFDB_MODE: "multi"
      LEIFDB_HOST: "leifdb0"
      LEIFDB_MEMBER_NODES: "leifdb0:16990,leifdb1:16991,leifdb2:16992"
  leifdb1:
    build: .
    ports:
      - "8081:8081"
      - "16991:16991"
    environment:
      LEIFDB_MODE: "multi"
      LEIFDB_HOST: "leifdb1"
      LEIFDB_HTTP_PORT: 8081
      LEIFDB_RAFT_PORT: 16991
      LEIFDB_MEMBER_NODES: "leifdb0:16990,leifdb1:16991,leifdb2:16992"
  leifdb2:
    build: .
    ports:
      - "8082:8082"
      - "16992:16992"
    environment:
      LEIFDB_MODE: "multi"
      LEIFDB_HOST: "leifdb2"
      LEIFDB_HTTP_PORT: 8082
      LEIFDB_RAFT_PORT: 16992
      LEIFDB_MEMBER_NODES: "leifdb0:16990,leifdb1:16991,leifdb2:16992"
  leifui:
    build: ./ui/
    ports:
      - "3000:3000"
