#!/usr/bin/env bash

# Remove comments that take the exact form:
#
# /*
#  */
#
# (with whitespace visualized: `\*\n */`)
#
# Replace with:
#
# /* eslint-disable */
#
# This takes files generated by autorest using --license-header=NONE and adds
# the eslint directive needed to suppress a warning that was causing CI build
# to fail on an eslint warning for generated code.
# Cross-reference: https://github.com/Azure/autorest.typescript/issues/669
# and: https://github.com/facebook/create-react-app/issues/2339

for FILENAME in "$@"
do
  perl -0777 -i -pe 's/\/\*\n \*\//\/\* eslint-disable \*\//s' $FILENAME
done
