version: 2.1
orbs:
  go: circleci/go@1.7.3
jobs:
  build:
    executor:
      name: go/default
      tag: '1.17'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: go test -v --tags=unit ./...
      - run: go test -v --tags=mgmttest ./...
workflows:
  main:
    jobs:
      - build
