// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.1
// source: persistence.proto

package persistence

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LogRecord_Action int32

const (
	LogRecord_SET LogRecord_Action = 0
	LogRecord_DEL LogRecord_Action = 1
)

// Enum value maps for LogRecord_Action.
var (
	LogRecord_Action_name = map[int32]string{
		0: "SET",
		1: "DEL",
	}
	LogRecord_Action_value = map[string]int32{
		"SET": 0,
		"DEL": 1,
	}
)

func (x LogRecord_Action) Enum() *LogRecord_Action {
	p := new(LogRecord_Action)
	*p = x
	return p
}

func (x LogRecord_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogRecord_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_persistence_proto_enumTypes[0].Descriptor()
}

func (LogRecord_Action) Type() protoreflect.EnumType {
	return &file_persistence_proto_enumTypes[0]
}

func (x LogRecord_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogRecord_Action.Descriptor instead.
func (LogRecord_Action) EnumDescriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{0, 0}
}

type LogRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term   int64            `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Action LogRecord_Action `protobuf:"varint,2,opt,name=action,proto3,enum=persistence.LogRecord_Action" json:"action,omitempty"`
	Key    string           `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value  string           `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persistence_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{0}
}

func (x *LogRecord) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogRecord) GetAction() LogRecord_Action {
	if x != nil {
		return x.Action
	}
	return LogRecord_SET
}

func (x *LogRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*LogRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persistence_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{1}
}

func (x *Log) GetRecords() []*LogRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_persistence_proto protoreflect.FileDescriptor

var file_persistence_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x9a, 0x01, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x65,
	0x72, 0x6d, 0x12, 0x35, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65,
	0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x1a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x53,
	0x45, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x45, 0x4c, 0x10, 0x01, 0x22, 0x37, 0x0a,
	0x03, 0x4c, 0x6f, 0x67, 0x12, 0x30, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x63, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x74, 0x6d, 0x6f, 0x72, 0x72, 0x2f, 0x6c, 0x65, 0x69, 0x66,
	0x64, 0x62, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x65, 0x72, 0x73,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_persistence_proto_rawDescOnce sync.Once
	file_persistence_proto_rawDescData = file_persistence_proto_rawDesc
)

func file_persistence_proto_rawDescGZIP() []byte {
	file_persistence_proto_rawDescOnce.Do(func() {
		file_persistence_proto_rawDescData = protoimpl.X.CompressGZIP(file_persistence_proto_rawDescData)
	})
	return file_persistence_proto_rawDescData
}

var file_persistence_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_persistence_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_persistence_proto_goTypes = []interface{}{
	(LogRecord_Action)(0), // 0: persistence.LogRecord.Action
	(*LogRecord)(nil),     // 1: persistence.LogRecord
	(*Log)(nil),           // 2: persistence.Log
}
var file_persistence_proto_depIdxs = []int32{
	0, // 0: persistence.LogRecord.action:type_name -> persistence.LogRecord.Action
	1, // 1: persistence.Log.records:type_name -> persistence.LogRecord
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_persistence_proto_init() }
func file_persistence_proto_init() {
	if File_persistence_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_persistence_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persistence_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_persistence_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_persistence_proto_goTypes,
		DependencyIndexes: file_persistence_proto_depIdxs,
		EnumInfos:         file_persistence_proto_enumTypes,
		MessageInfos:      file_persistence_proto_msgTypes,
	}.Build()
	File_persistence_proto = out.File
	file_persistence_proto_rawDesc = nil
	file_persistence_proto_goTypes = nil
	file_persistence_proto_depIdxs = nil
}
