definitions:
  main.DeleteResponse:
    properties:
      status:
        type: string
    type: object
  main.HealthResponse:
    properties:
      status:
        type: string
      version:
        type: string
    type: object
  main.ReadResponse:
    properties:
      value:
        type: string
    type: object
  main.WriteRequest:
    properties:
      value:
        type: string
    type: object
  main.WriteResponse:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
  description: A distributed K-V store using the Raft protocol
  license:
    name: MIT
    url: https://github.com/btmorr/leifdb/blob/edge/LICENSE
  title: LeifDb Client API
  version: "0.1"
paths:
  /db/{key}:
    delete:
      consumes:
      - '*/*'
      operationId: db-delete
      parameters:
      - description: Key
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.DeleteResponse'
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirect address of current leader
              type: string
          schema:
            type: string
      summary: Delete item from database by key
    get:
      consumes:
      - '*/*'
      operationId: db-read
      parameters:
      - description: Key
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ReadResponse'
      summary: Return value from database by key
    put:
      consumes:
      - application/json
      operationId: db-write
      parameters:
      - description: Key
        in: path
        name: key
        required: true
        type: string
      - description: Value
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.WriteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.WriteResponse'
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirect address of the current leader
              type: string
          schema:
            type: string
        "400":
          description: Error message
          schema:
            type: string
      summary: Write value to database by key
  /health:
    get:
      consumes:
      - '*/*'
      operationId: http-health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.HealthResponse'
      summary: Return server health status
swagger: "2.0"
